add_newline = false
format = """$directory$character"""
right_format = """$all"""
command_timeout = 1000

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
vicmd_symbol = '[N](bold yellow)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
